In [1]:
import numpy as np
import matplotlib.pyplot as plt
from src.core.pybullet_core import PybulletCore
from src.utils import *

# Open Pybullet GUI

In [2]:
pb = PybulletCore()
pb.connect(robot_name = "indy7_v2", joint_limit=True, constraint_visualization = False)

******** ROBOT INFO ********
Robot name: indy7_v2
Robot type: indy7_v2
DOF: 6
Joint limit: True
Constraint visualization: False


# Move robot

In [3]:
pb.MoveRobot([0, 30, -120, 0, -90, 0], degree=True, verbose=True)

***** Set desired joint angle *****
[ 0.      0.5236 -2.0944  0.     -1.5708  0.    ]


# Get robot's current state

In [6]:
q = pb.my_robot.q
PRINT_YELLOW("Joint position (rad)", q.T)

qdot = pb.my_robot.qdot
PRINT_YELLOW("Joint velocity (rad/s)", qdot.T)

T_end = pb.my_robot.T_end
PRINT_YELLOW("End-effector's pose in SE3\n", T_end)

Jr = pb.my_robot.Jr
PRINT_YELLOW("Robot's Jacobian\n", Jr)


Joint position (rad): [[ 0.      0.5236 -2.0944  0.     -1.5708  0.    ]]
Joint velocity (rad/s): [[-0. -0.  0.  0.  0. -0.]]
End-effector's pose in SE3
: [[-1.     -0.     -0.      0.125 ]
 [-0.      1.     -0.     -0.2025]
 [ 0.     -0.     -1.      0.6372]
 [ 0.      0.      0.      1.    ]]
Robot's Jacobian
: [[ 0.2025 -0.3377  0.052  -0.      0.052   0.    ]
 [ 0.125   0.      0.      0.052   0.      0.    ]
 [ 0.      0.125   0.35   -0.199  -0.     -0.    ]
 [ 0.     -0.     -0.     -1.     -0.     -0.    ]
 [-0.     -1.     -1.     -0.     -1.     -0.    ]
 [-1.      0.      0.     -0.      0.      1.    ]]


# Rotation & Transformation Matrix Utils

In [7]:
# Euler angle -> Rotation matrix
R = eul2Rot([90, 0, 0], seq='XYZ', degree=True)
print(R)

# Rotation matrix -> Euler angle
eul = Rot2eul(R, seq='XYZ', degree=True)
print(eul)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
[90.  0.  0.]


In [8]:
# xyz position + Euler angle -> Transformation matrix
T = xyzeul2SE3([0.2, 0.3, 0.4], [90, 0, 0], seq='XYZ', degree=True)
print(T)

# Transformation matrix -> xyz position + Euler angle
xyz = T[0:3, 3]
eul = Rot2eul(T[0:3, 0:3], seq='XYZ', degree=True)
print(xyz, eul)

[[ 1.   0.   0.   0.2]
 [ 0.   0.  -1.   0.3]
 [ 0.   1.   0.   0.4]
 [ 0.   0.   0.   1. ]]
[0.2 0.3 0.4] [90.  0.  0.]


# Matrix Exponential/Logarithm (Out of this course!)

In [9]:
R = eul2Rot([90, 0, 0], seq='XYZ', degree=True)
print(R)

# Rotation matrix -> 3-by-1 vector (log)
xi = Rot2Vec(R)
print(xi)

# 3-by-1 vector -> rotation matrix (exp)
R = Vec2Rot(xi)
print(R)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
[[1.5708]
 [0.    ]
 [0.    ]]
[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [10]:
pb.disconnect()

Disconnect Success!
