http://docs.neuromeka.com/3.2.0/kr/IndyAPI/indydcp3_python/

In [1]:
import os
import sys

import numpy as np
import matplotlib.pyplot as plt
import time

sys.path.append("../")

from src.utils import *
from src.core.pybullet_core import PybulletCore

from neuromeka import IndyDCP3

# Connect to Indy7
***
- **Robot #1**: 192.168.0.8
- **Robot #2**: 192.168.0.11
- **Robot #3**: 192.168.0.12
- **Robot #4**: 192.168.0.13
- **Robot #5**: 192.168.0.10
- **Robot #6**: 192.168.0.9
***
<img src="./figures/indy7v2_image.jpg" width="20%" height="20%"></img>

In [2]:
indy = IndyDCP3(robot_ip='192.168.0.10', index=0)

# Real-time Data Acquisition Functions
http://docs.neuromeka.com/3.2.0/kr/IndyAPI/indydcp3_python/#_3

### get_motion_data()
: Information on Motion Data

In [ ]:
motion_data = indy.get_motion_data()
for key, value in zip(motion_data.keys(), motion_data.values()):
    PRINT_YELLOW(key, value)

traj_progress: 100
is_target_reached: True
speed_ratio: 100
cur_traj_progress: 100
traj_state: 0
is_in_motion: False
is_pausing: False
is_stopping: False
has_motion: False
motion_id: 0
remain_distance: 0.0
motion_queue_size: 0


### get_control_data()
: Information on Control Data

In [ ]:
control_data = indy.get_control_data()
for key, value in zip(control_data.keys(), control_data.values()):
    PRINT_YELLOW(key, value)

running_hours: 4
running_mins: 10
running_secs: 15
op_state: 5
q: [-0.008444037, -14.994068, -75.005615, 0.0008702042, -90.00397, 0.00027193883]
qdot: [0.3631844, -0.0, 0.5447766, -0.0, -0.0, -0.0]
p: [466.38718, -202.56718, 632.1776, 179.99913, -0.0036525244, 179.99129]
pdot: [2.2586207, 2.9561744, 3.3277888, 2.056743e-05, -0.5447711, -0.36319268]
ref_frame: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
tool_frame: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
sim_mode: False


### get_violation_data()
: Information on Violation Data

In [ ]:
violation_data = indy.get_violation_data()
for key, value in zip(violation_data.keys(), violation_data.values()):
    PRINT_YELLOW(key, value)

j_index: 1
i_args: [0]
f_args: [-1273549.8]
violation_code: 0
violation_str: 


# Motion Command Data Related Functions
http://docs.neuromeka.com/3.2.0/kr/IndyAPI/indydcp3_python/#_5

### stop_motion(stop_category)
: Stops motion in the specified manner (IMMEDIATE_BRAKE, SMOOTH_BRAKE, SMOOTH_ONLY)

In [6]:
IMMEDIATE_BRAKE = 0 # cat0 stop
SMOOTH_BRAKE = 1    # cat1 stop
SMOOTH_ONLY = 2     # cat2 stop
stop_response = indy.stop_motion(stop_category=SMOOTH_ONLY)

### movej(...)
: Moves the robot to the specified joint target position with various conditions.
***
### Arguments
- **jtarget**         : List value in degrees (ex. **jtarget**=[0, -22, 100, 0, 100, 0])
- **blending_type**   : Motion blending types (0: no blending, 1: override blending, 2: duplicate blending)
- **base_type**       : reference joint frame types (0: alsolute joint values, 1: relative joint values)
- **blending_radius** : blending radius betweem each via-points
- **vel_ratio**       : motion velocity level (0~100)
- **acc_ratio**       : motion acceleration level (0~900)

### [Asynchronized motion blending] Overrive vs Duplicate
<img src="./figures/asynchronized.png" width="45%" height="45%"></img>

In [ ]:
### Joint motion 1
target_pos = [0, -22, 100, 0, 100, 0]
move_response = indy.movej(jtarget=target_pos)
print(move_response)

PRINT_BLUE("*** Robot's motion info ***")
motion_data = indy.get_motion_data()
PRINT_YELLOW("is_in_motion", motion_data["is_in_motion"])
PRINT_YELLOW("is_target_reached", motion_data["is_target_reached"])
PRINT_YELLOW("has_motion", motion_data["has_motion"])
print()

time.sleep(7)

PRINT_BLUE("*** Robot's motion info ***")
motion_data = indy.get_motion_data()
PRINT_YELLOW("is_in_motion", motion_data["is_in_motion"])
PRINT_YELLOW("is_target_reached", motion_data["is_target_reached"])
PRINT_YELLOW("has_motion", motion_data["has_motion"])
print()
    
### Joint motion 2
target_pos = [0, -15, -75, 0, -90, 0]
move_response = indy.movej(jtarget=target_pos)
print(move_response)

PRINT_BLUE("*** Robot's motion info ***")
motion_data = indy.get_motion_data()
PRINT_YELLOW("is_in_motion", motion_data["is_in_motion"])
PRINT_YELLOW("is_target_reached", motion_data["is_target_reached"])
PRINT_YELLOW("has_motion", motion_data["has_motion"])
print()

time.sleep(7)

PRINT_BLUE("*** Robot's motion info ***")
motion_data = indy.get_motion_data()
PRINT_YELLOW("is_in_motion", motion_data["is_in_motion"])
PRINT_YELLOW("is_target_reached", motion_data["is_target_reached"])
PRINT_YELLOW("has_motion", motion_data["has_motion"])
print()

{'code': '0', 'msg': ''}
*** Robot's motion info ***
is_in_motion: True
is_target_reached: False
has_motion: True

*** Robot's motion info ***
is_in_motion: False
is_target_reached: True
has_motion: False

{'code': '0', 'msg': ''}
*** Robot's motion info ***
is_in_motion: True
is_target_reached: False
has_motion: True

*** Robot's motion info ***
is_in_motion: False
is_target_reached: True
has_motion: False



In [8]:
NO_BLENDING = 0
OVERRIDE_BLENDING = 1
DUPLICATE_BLENDING = 2

target_pos1 = [50, -22, 100, 0, 100, 0]
target_pos2 = [0, -22, 100, 0, 100, 0]

indy.movej(target_pos1, blending_type=OVERRIDE_BLENDING)
time.sleep(0.5)
indy.movej(target_pos2, blending_type=OVERRIDE_BLENDING)

{'code': '0', 'msg': ''}

In [9]:
ABSOLUTE_JOINT = 0
RELATIVE_JOINT = 1

target_pos1 = [-30, 0, 0, 0, 0, 0]

# move_response = indy.movej(target_pos1, blending_type=NO_BLENDING, base_type=ABSOLUTE_JOINT, vel_ratio=50, acc_ratio=100)
move_response = indy.movej(target_pos1, blending_type=NO_BLENDING, base_type=RELATIVE_JOINT, vel_ratio=50, acc_ratio=100)
print(move_response)

{'code': '0', 'msg': ''}


# movej_time(...)
: Moves the robot to the joint target position over a specified time.
***
### Arguments
- **jtarget**         : List value in degrees (ex. **jtarget**=[0, -22, 100, 0, 100, 0])
- **blending_type**   : Motion blending types (0: no blending, 1: override blending, 2: duplicate blending)
- **base_type**       : reference joint frame types (0: alsolute joint values, 1: relative joint values)
- **blending_radius** : blending radius betweem each via-points
- **move_time**       : entire movement time (sec)

# movel(...), movel_time(...)
: Moves the robot linearly to the specified task target position with various conditions.
***
### Arguments
- **ttarget**         : List value in [xyz(mm), eul_xyz(deg)] (ex. **ttarget**=[0.4, 0, 0.4, 0, 180, 0])
- **blending_type**   : Motion blending types (0: no blending, 1: override blending, 2: duplicate blending)
- **base_type**       : reference task frame types (0: alsolute world frame, 1: relative world frame, 2: relative TCP frame)
- **blending_radius** : blending radius betweem each via-points
- (movel) **vel_ratio**       : motion velocity level (0~100)
- (movel) **acc_ratio**       : motion acceleration level (0~900)
- (movel_time) **move_time**       : entire movement time (sec)
***
<img src="./figures/BaseFrame.png" width="90%" height="90%"></img>

# Inverse Kinematics & Direct Teaching Mode
***
http://docs.neuromeka.com/3.2.0/en/IndyAPI/indydcp3_python/#inverse-kinematics-and-simulation-mode-related-functions

### inverse_kin(tpos, init_jpos)
: A function that calculates the joint positions that can reach a given task space coordinate, based on the initial joint positions.
***
### Arguments
- **tpos**         : Target task space position (ex. **tpos**=[0.4, 0, 0.4, 0, 180, 0])
- **init_jpos**   : Initial joint position
***
### Return
- **jpos**         : List of calculated joint positions

In [ ]:
tpos = indy.get_control_data()['p']
init_jpos = indy.get_control_data()['q']

print("Current tpos", tpos)
print("Current jpos", init_jpos)

ik_data = indy.inverse_kin(tpos, init_jpos)
PRINT_YELLOW("jpos", ik_data["jpos"])
PRINT_YELLOW("response", ik_data["response"])

Current tpos [-254.95837, -86.28541, 687.52057, 179.9992, -1.9892104, 149.90483]
Current jpos [-30.094912, -22.003073, 100.00827, -0.0007614287, 100.005714, 5.438776e-05]
jpos: [-30.094912, -22.003073, 100.00827, -0.0007614287, 100.005714, 5.438776e-05]
response: {'msg': 'InverseKinematics Success', 'code': '0'}


### set_direct_teaching(enable)
: Switching to the direct teaching mode.
***
### Arguments
- **enable**         : Enable/Disable direct teaching mode via True/False (Bool)

In [11]:
indy.set_direct_teaching(enable=True)

{'msg': 'SetDirectTeaching Success', 'code': '0'}

In [12]:
indy.set_direct_teaching(enable=False)

{'msg': 'SetDirectTeaching Success', 'code': '0'}

In [103]:
indy.set_friction_comp(
    control_comp=False, 
    control_comp_levels=[5, 5, 5, 5, 5, 5],
    dt_comp=True,
    dt_comp_levels=[2, 5, 2, 2, 5, 5]
)

{'code': '0', 'msg': ''}

In [104]:
indy.set_direct_teaching(enable=True)

{'msg': 'SetDirectTeaching Success', 'code': '0'}

In [105]:
indy.set_direct_teaching(enable=False)

{'msg': 'SetDirectTeaching Success', 'code': '0'}

### recover()
: A function to recover the robot from error or collision situations. When the robot falls into an abnormal state, calling this function can restore it to normal condition.

In [13]:
indy.recover()

{'msg': 'Success', 'code': '0'}

# Future works 
### (TODO... Out of the scope of this course! (For an Advanced Robotics))
- Customized low-level torque controller using IndySDK3.0

***

# Real Indy7 with PyBullet simulation

In [14]:
pb = PybulletCore()
pb.connect(robot_name = "indy7_v2", joint_limit=True, constraint_visualization = False)

******** ROBOT INFO ********
Robot name: indy7_v2
Robot type: indy7_v2
DOF: 6
Joint limit: True
Constraint visualization: False


In [15]:
def sync_indy():
    q = indy.get_control_data()['q']
    pb.MoveRobot(q, degree=True)
    return

In [ ]:
def wait_indy():
    while True:
        sync_indy()
        if not indy.get_motion_data()["is_in_motion"]:
            break
        #time.sleep(0.1)
        time.sleep(0.001)
    PRINT_YELLOW("Move done!!")
    return

In [17]:
def movej_indy(q, degree=True, blending_type=0):
    q = np.asarray(q).reshape(-1)
    if not degree:
        q = q * 180/np.pi
        
    indy.movej(q, blending_type=blending_type, acc_ratio=50)
    pb.MoveRobot(q, degree=True)
    return

# def movec_indy(T, blending_type=0):
    
#     p = SE3    
#     indy.movej(q, blending_type=blending_type, acc_ratio=50)
#     #pb.MoveRobot(q, degree=True)
#     return

# Straight-line in task space (Built-in function)

### Move to init pose

In [18]:
q_i = np.array([0, -15, -75, 0, -90, 0])*np.pi/180
movej_indy(q_i, degree=False)

wait_indy()

T_i = pb.my_robot.pinModel.FK(q_i)

p_i = indy.get_control_data()["p"]
print(p_i)
T_i_from_indy = xyzeul2SE3([x/1000 for x in p_i[0:3]], [x for x in p_i[3:6]], degree=True, seq='XYZ')


print(T_i)
print(T_i_from_indy)
pb.add_debug_frames([T_i])

Move done!!
[466.4955, -202.44437, 632.1067, -0.00010875141, -179.98729, 0.0067009395]
[[-1.     -0.     -0.      0.4665]
 [ 0.      1.     -0.     -0.2025]
 [ 0.     -0.     -1.      0.6322]
 [ 0.      0.      0.      1.    ]]
[[-1.      0.0001 -0.0002  0.4665]
 [ 0.0001  1.     -0.     -0.2024]
 [ 0.0002 -0.     -1.      0.6321]
 [ 0.      0.      0.      1.    ]]


In [19]:
p_f = [600, 0, 400, 0, 90, 0]

T_f = xyzeul2SE3([x/1000 for x in p_f[0:3]], [x for x in p_f[3:6]], degree=True, seq='XYZ')

pb.add_debug_frames([T_f])

In [20]:
indy.movel(p_f, vel_ratio=25, acc_ratio=100)

{'msg': 'MoveL Success', 'code': '0'}

In [ ]:
violation_data = indy.get_violation_data()
for key, value in zip(violation_data.keys(), violation_data.values()):
    PRINT_YELLOW(key, value)

violation_code: 8192
j_index: 3
i_args: [0]
f_args: [-84363.336]
violation_str: Standstill Failed


In [23]:
indy.recover()

{'msg': 'Success', 'code': '0'}

In [24]:
q_i = np.array([0, -15, -75, 0, -90, 0])*np.pi/180
movej_indy(q_i, degree=False)

wait_indy()

T_i = pb.my_robot.pinModel.FK(q_i)

p_i = indy.get_control_data()["p"]
print(p_i)
T_i_from_indy = xyzeul2SE3([x/1000 for x in p_i[0:3]], [x for x in p_i[3:6]], degree=True, seq='XYZ')


print(T_i)
print(T_i_from_indy)
pb.add_debug_frames([T_i])

Move done!!
[466.45334, -202.58162, 632.1513, 179.99419, -0.0020358274, 179.99207]
[[-1.     -0.     -0.      0.4665]
 [ 0.      1.     -0.     -0.2025]
 [ 0.     -0.     -1.      0.6322]
 [ 0.      0.      0.      1.    ]]
[[-1.     -0.0001 -0.      0.4665]
 [-0.0001  1.     -0.0001 -0.2026]
 [ 0.     -0.0001 -1.      0.6322]
 [ 0.      0.      0.      1.    ]]


In [27]:
T = 5
dT = 0.001

num_points = int(T/dT)

a = np.linalg.solve([[1, 0, 0, 0],
                     [1, T, T**2, T**3],
                     [0, 1, 0, 0],
                     [0, 1, 2*T, 3*T**2]],
                     [0, 1, 0, 0])

q_i = pb.my_robot.q
qlist = np.zeros([6, 0])
qlist = np.concatenate((qlist, q_i), axis=1)
T_start = pb.my_robot.pinModel.FK(q_i)
T_end = T_f

trajectories = []
trajectories_debug = []

pb.add_debug_frames([T_end])

p_start = T_start[0:3, [3]]
p_end = T_end[0:3, [3]]

R_start = T_start[0:3, 0:3]
R_end = T_end[0:3, 0:3]


for i in range(num_points):

    t = T * (i+1) / num_points

    s = np.dot(a, [1, t, t**2, t**3])
    
    p_goal = p_start + s * (p_end - p_start)
    R_goal = R_start @ Vec2Rot( Rot2Vec( R_start.T @ R_end ) * s )

    T_goal = np.eye(4)
    T_goal[0:3, [3]] = p_goal
    T_goal[0:3, 0:3] = R_goal
    
    trajectories.append(T_goal)
    if i%200 == 0:
        trajectories_debug.append(T_goal)
        pb.add_debug_frames(trajectories_debug + [T_end])
        

    T_i = pb.my_robot.pinModel.FK(q_i)
    Jb_i = pb.my_robot.pinModel.Jb(q_i)
    
    R_i = T_i[0:3, 0:3]
    A_upper = np.concatenate((np.zeros([3, 3]), R_i), axis=1)
    A_lower = np.concatenate((np.eye(3), np.zeros([3, 3])), axis=1)
    A = np.concatenate((A_upper, A_lower), axis=0)

    Jv_i = A @ Jb_i
    
    r_err = T_goal[0:3, [3]] - T_i[0:3, [3]]
    
    # ==== IK using exponential coordinate ====
    R_err = T_i[0:3, 0:3].T @ T_goal[0:3, 0:3]
    xi_err = Rot2Vec(R_err)
    p_err = np.concatenate((r_err, xi_err), axis=0)
    
    q_i = q_i + 1 * Jv_i.T @ np.linalg.pinv(Jv_i @  Jv_i.T + 1e-3 * np.eye(6)) @ p_err

    qlist = np.concatenate((qlist, q_i), axis=1)
    #pb.MoveRobot(q_i, degree=False)
    #time.sleep(T/num_points/1000)

In [28]:
indy.start_teleop(0)
time.sleep(1)

idx  = 0
ttic = time.time()

while True:
    tic = time.time()
    
    T_des = trajectories[idx]
    p_des = np.zeros(6)
    p_des[0:3] = 1000*T_des[0:3, 3]
    p_des[3:6] = Rot2eul(T_des[0:3, 0:3], seq='XYZ', degree=True)
    
    indy.movetelel_abs(p_des, vel_ratio=0.5, acc_ratio=1)
#     sync_indy()
    toc = time.time()
    
    didx = int((toc-tic)//dT)+1
    
#     print(toc-tic, dT*(didx) - (toc-tic), didx)
#     time.sleep(dT*(didx) - (toc-tic))
        
    idx = idx + didx
    
    if idx >= num_points:
        break
        
wait_indy()

ttoc = time.time()

indy.stop_teleop()

Move done!!


{'msg': 'TeleOp Stop Requested', 'code': '0'}

In [ ]:
q_i = np.array([0, -15, -75, 0, -90, 0])*np.pi/180
movej_indy(q_i, degree=False)

wait_indy()

T_i = pb.my_robot.pinModel.FK(q_i)

p_i = indy.get_control_data()["p"]
print(p_i)
T_i_from_indy = xyzeul2SE3([x/1000 for x in p_i[0:3]], [x for x in p_i[3:6]], degree=True, seq='XYZ')


print(T_i)
print(T_i_from_indy)
pb.add_debug_frames([T_i])

In [ ]:
indy.start_teleop(0)
time.sleep(1)

idx  = 0
ttic = time.time()

while True:
    tic = time.time()
    
    T_des = trajectories[idx]
    p_des = np.zeros(6)
    p_des[0:3] = 1000*T_des[0:3, 3]
    p_des[3:6] = Rot2eul(T_des[0:3, 0:3], seq='XYZ', degree=True)
    
    indy.movetelel_abs(p_des, vel_ratio=0.5, acc_ratio=1)
#     sync_indy()
    toc = time.time()
    
    didx = int((toc-tic)//dT)+1
    
#     print(toc-tic, dT*(didx) - (toc-tic), didx)
#     time.sleep(dT*(didx) - (toc-tic))
        
    idx = idx + didx
    
    if idx >= num_points:
        break
        
wait_indy()

ttoc = time.time()

indy.stop_teleop()

In [ ]:
indy.recover()